server:
  port: 8080

spring:
    datasource:
      name: test
      url: jdbc:mysql://140.143.53.168:3306/taotao
      username: root
      password: zk666
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    thymeleaf:
      mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.huaguoguo.taotao.dao
  config-location: classpath:mybatis/mybatis.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



