server:
  port: 8082

spring:
    thymeleaf:
      mode: LEGACYHTML5
    application:
      name: taotao-portal

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/




